source 'https://github.com/CocoaPods/Specs.git'

project '../bc.xcodeproj'
workspace '../bc.xcworkspace'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'bc' do
	post_install do |installer|
		installer.pods_project.targets.each do |target|
			target.build_configurations.each do |config|
				config.build_settings['ENABLE_BITCODE'] = 'NO'
				config.build_settings['SWIFT_VERSION'] = '4.2'
			end
		end
	end
end
