name: bc
configs:
    appstore_debug: debug
    appstore_stage: release
    appstore_release: release
    enterprise_stage: release
    enterprise_release: release
targets:
    bc:
        scheme: {}
        type: application
        platform: iOS
        deploymentTarget: "9.0"
        sources:
            - path: "../../src"
        settings:
            base:
                CODE_SIGN_STYLE: Manual
                SWIFT_VERSION: 4.2
                TARGETED_DEVICE_FAMILY: 1
            configs:
                appstore_debug:
                    INFOPLIST_FILE: "support/appstore_debug.Info.plist"
                    PRODUCT_BUNDLE_IDENTIFIER: su.koren.bc
                appstore_stage:
                    INFOPLIST_FILE: "support/appstore_stage.Info.plist"
                    PRODUCT_BUNDLE_IDENTIFIER: su.koren.bc
                appstore_release:
                    INFOPLIST_FILE: "support/appstore_release.Info.plist"
                    PRODUCT_BUNDLE_IDENTIFIER: su.koren.bc
                enterprise_stage:
                    INFOPLIST_FILE: "support/enterprise_stage.Info.plist"
                    PRODUCT_BUNDLE_IDENTIFIER: su.koren.bc.enterprise
                enterprise_release:
                    INFOPLIST_FILE: "support/enterprise_release.Info.plist"
                    PRODUCT_BUNDLE_IDENTIFIER: su.koren.bc.enterprise
